BASE <http://example.org/>
SELECT * WHERE {
  VALUES (?a ?b) {
    (<http://example.org/a1> <http://example.org/b1>)
    (<http://example.org/a2> <http://example.org/b2>)
    (<http://example.org/a3> <http://example.org/b3>)
  }
  FILTER(?a IN(<http://example.org/a1>, <http://example.org/a2>))
}