BASE <http://example.org/>

SELECT * WHERE {
  QUERY ?q1 {
    SELECT * WHERE {
      VALUES (?a ?b) FROM ?q2

      FILTER(?a IN (<a1>, <a2>))
    }
  }

  QUERY ?q2 {
    SELECT * WHERE {
      VALUES (?a ?b) {
        (<a1> <b1>)
        (<a2> <b2>)
        (<a3> <b3>)
        (<a4> <b4>)
      }

      FILTER(?a IN (<a1>, <a2>, <a3>))
    }
  }

  VALUES (?a ?b) FROM ?q1
}