PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wp: <http://vocabularies.wikipathways.org/wp#>

SELECT DISTINCT ?item ?pw_annotation ?annotation_label WHERE {
  QUERY ?query {
    SELECT ?item ?source_pathway WHERE {
      ?item wdt:P2410 ?wpid;
        wdt:P2888 ?source_pathway;
        rdfs:label ?label.

      FILTER(CONTAINS(LCASE(?label), "vitamin"))
    }
  }

  SERVICE <http://sparql.wikipathways.org/sparql> {
     VALUES (?item ?source_pathway) FROM ?query

     ?wp_pathway dc:identifier ?source_pathway .
     ?wp_pathway wp:ontologyTag ?pw_annotation .
     ?pw_annotation rdfs:label ?annotation_label .
   }
} LIMIT 100